#server:
  #address: 0.0.0.0
  #port : ${PORT}

spring:
  # .env import
  #config:
    #import: optional:file:.env[.properties]
  profiles:
    active: prod  # 기본은 dev 환경

  cloud:
    aws:
      s3:
        bucket: typinggame-profile
        region: ap-northeast-2
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}