spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: true
      path: /h2-console
  # JDBC URL
  datasource:
    url: jdbc:mysql://localhost:3306/typing_game
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true