server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    url:  jdbc:mysql://typing-game.chgc06cgchah.ap-southeast-2.rds.amazonaws.com:3306/typing_game?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_USERNAME}
    password: ${AWS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate    # 개발용: update / 운영: validate 또는 none

    show-sql: true           # 필요하면 true로 SQL 로그 확인 가능
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#typing-game-db.internal

