# H2 Console ???
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# JDBC URL ??
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

# JPA ??
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true