spring:
  datasource:
    url: jdbc:mysql://localhost:3306/typing_game?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root          # Docker에서 설정한 root 계정
    password: 961210  # Docker에서 설정한 비밀번호
  jpa:
    hibernate:
      ddl-auto: create-drop      # 개발용: update / 운영: validate 또는 none
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true           # 필요하면 true로 SQL 로그 확인 가능
    properties:
      hibernate.format_sql: true