spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # JDBC URL
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  #JPA
  jpa:
    hibernate:
     ddl-auto: create-drop
     show-sql: true